apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jira-demo-service
  description: Demo service showcasing Jira dashboard integration
  annotations:
    # Jira Dashboard Plugin Integration
    jira.com/project-key: "ETP"                    # Required: Project key
    jira.com/filter-id: "10566"                    # Optional: Saved filter ID
    jira.com/component: "backend"                  # Optional: Component filter
    
    # Additional metadata
    github.com/project-slug: "eon-energy/espresso-demo"
    backstage.io/techdocs-ref: "dir:."
    
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: demo-platform
