apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-jira-component
  namespace: default
  description: Demo service showcasing Jira integration with Espresso Test Project
  tags:
    - demo
    - jira
    - nodejs
  annotations:
    # Jira project key (required for tab to appear)
    jira/project-key: ETP
    # Jira filter ID (optional - filters issues shown)
    jira/filter-id: "10566"
    jira/component: "backend"
    # github.com/project-slug: "eon-energy/espresso-demo"
spec:
  type: service
  lifecycle: experimental
  owner: group:default/team-a
  system: demo-platform

