---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simple-app
  description: A simple web application deployed via Backstage
  annotations:
    github.com/project-slug: PawelWaj/simple-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: web-apps

---
apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: simple-app-template
  description: Template for creating a simple web app in Backstage
spec:
  type: service
  owner: guest
  parameters:
    - title: App Name
      type: string
      description: Unique name for your app
      default: my-simple-app
    - title: Owner
      type: string
      description: Owner of the app (e.g., username or team)
      default: guest
  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          appName: '{{ parameters.App Name }}'
          owner: '{{ parameters.Owner }}'
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        catalogInfoPath: '/catalog-info.yaml'  # Path to generated file in temp workspace