---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simple-app
  description: A simple web application deployed via Backstage
  annotations:
    github.com/project-slug: PawelWaj/simple-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: web-apps

---
apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: simple-app-template
  description: Template for creating and deploying a simple web app
spec:
  type: service
  owner: guest
  parameters:
    - title: App Name
      type: string
      description: Unique name for your app
      default: my-simple-app
    - title: Repository Name
      type: string
      description: GitHub repository name (must be unique in your org)
      default: my-simple-app-repo
    - title: Owner
      type: string
      description: Owner of the app (e.g., username or team)
      default: guest
  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          appName: '{{ parameters.App Name }}'
          repoName: '{{ parameters.Repository Name }}'
          owner: '{{ parameters.Owner }}'
    - id: publish-github
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: 'A simple app created via Backstage'
        repoUrl: 'github.com?owner=PawelWaj&repo={{ parameters.Repository Name }}'
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: 'https://github.com/PawelWaj/{{ parameters.Repository Name }}/blob/main/catalog-info.yaml'
        catalogInfoPath: '/catalog-info.yaml'