apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: environment-template
  title: Azure Environment Template
  description: Create a new Azure Environment with specified configuration and security setup
  tags:
    - azure
    - environment
    - cloud
    - cnlz
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Environment Configuration
      required:
        - name
        - subscription
      properties:
        name:
          title: Environment Name
          type: string
          description: Unique name for the Azure environment
          pattern: '^[a-zA-Z0-9-_]+$'
        subscription:
          title: Azure Subscription
          type: string
          description: Azure subscription ID where the environment will be created
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        region:
          title: Azure Region
          type: string
          description: Primary Azure region for the environment
          enum:
            - eastus
            - westus2
            - westeurope
            - northeurope
            - eastasia
            - southeastasia
            - centralus
            - eastus2
          default: eastus
        environment_type:
          title: Environment Type
          type: string
          description: Type of environment being created
          enum:
            - development
            - staging
            - production
            - sandbox
          default: development
        resourceGroupPrefix:
          title: Resource Group Prefix
          type: string
          description: Prefix for resource group names in this environment
          pattern: '^[a-zA-Z0-9-_]+$'
          default: "rg"
    - title: Security & Compliance
      properties:
        enableWizSecurity:
          title: Enable Wiz Security
          type: boolean
          description: Enable Wiz security scanning and compliance monitoring
          default: true
        enableDefender:
          title: Enable Azure Defender
          type: boolean
          description: Enable Azure Defender for cloud security
          default: true
        enableActivityLog:
          title: Enable Activity Log
          type: boolean
          description: Enable Azure Activity Log for audit logging
          default: true
        enablePolicyCompliance:
          title: Enable Policy Compliance
          type: boolean
          description: Enable Azure Policy for compliance monitoring
          default: true
    - title: Networking Configuration
      properties:
        enableVNet:
          title: Enable Virtual Network
          type: boolean
          description: Create a virtual network for this environment
          default: true
        vnetAddressSpace:
          title: VNet Address Space
          type: string
          description: CIDR block for the virtual network
          default: "10.0.0.0/16"
          pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2}$'
        enablePrivateEndpoints:
          title: Enable Private Endpoints
          type: boolean
          description: Enable private endpoints for Azure services
          default: true
    - title: Provider Configuration
      properties:
        azureADProviderConfig:
          title: Azure AD Provider Config
          type: string
          description: Provider configuration reference for Azure AD
          default: "provider-azuread"
        azureRMProviderConfig:
          title: Azure RM Provider Config
          type: string
          description: Provider configuration reference for Azure Resource Manager
          default: "azure-provider"
        wizProviderConfig:
          title: Wiz Provider Config
          type: string
          description: Provider configuration reference for Wiz
          default: "provider-config-wiz"
  steps:
    - id: log
      name: Log Azure Environment Parameters
      action: debug:log
      input:
        message: 'Creating Azure Environment: ${{ parameters.name }}, Subscription: ${{ parameters.subscription }}, Region: ${{ parameters.region }}, Type: ${{ parameters.environment_type }}'
   
  output:
    text:
      - title: Azure Environment Summary
        content: |
          Azure Environment "${{ parameters.name }}" has been configured with:
          - Subscription: ${{ parameters.subscription }}
          - Region: ${{ parameters.region }}
          - Type: ${{ parameters.environment_type }}
          - Resource Group Prefix: ${{ parameters.resourceGroupPrefix }}
          - Wiz Security: ${{ parameters.enableWizSecurity }}
          - Azure Defender: ${{ parameters.enableDefender }}
          - Virtual Network: ${{ parameters.enableVNet }}
          - VNet Address Space: ${{ parameters.vnetAddressSpace }}